services:
  rusthole:
    build:
      context: .
    networks:
      - internal
    ports:
      - "53:53"
    
  reporting:
    build:
      context: .
    networks:
      - internal

networks:
  internal:
    driver: bridge
    